### ISSUE TITLE
Support for a single database URL parameter?

### ISSUE THREAD

**Issue by spantaleev** [mvrhov/mvrhovPhinxBundle#8]
Right now you need to pass multiple parameters (host, port, username, pass).

Symfony's [Doctrine guidance](https://symfony.com/doc/4.0/doctrine.html) changed in 4.0 from using multiple parameters to using a single parameter (usually passed as a `DATABASE_URL` environment variable).

It would be convenient, if the same environment variable could be passed to this bundle and have it work.

In such a sense, the configuration could become something like this:

```yaml
mvrhov_phinx:
    adapters:
        mysql: Phinx\Db\Adapter\MysqlAdapter
    environment:
        connection:
            url: '%env(resolve:DATABASE_URL)%'
            charset: UTF8
```
